const cfg=window.RITUMATI_CONFIG||{};
const ready=cfg.spreadsheetId&&!cfg.spreadsheetId.includes('YOUR_');
const fallbackStats={women_reached:1200,sessions:85,districts_reached:12,satisfaction:92,annual_goal:2000,annual_completed:1440};
const fallbackDistricts=[['Bokaro','Jamshedpur',true,180,95],['Chatra','',false,90,48],['Deoghar','',false,120,62],['Dhanbad','',true,260,135],['Dumka','',false,110,58],['East Singhbhum','Jamshedpur',true,300,155],['Garhwa','',false,75,41],['Giridih','',true,220,118],['Godda','',false,85,44],['Gumla','',false,95,50],['Hazaribagh','',true,240,126],['Jamtara','',false,80,43],['Khunti','',false,70,38],['Koderma','',false,85,45],['Latehar','',false,75,40],['Lohardaga','',false,90,47],['Pakur','',false,70,36],['Palamu','',false,150,78],['Ramgarh','',false,100,52],['Ranchi','',true,320,170],['Sahibganj','',false,90,46],['Seraikela-Kharsawan','',false,115,60],['Simdega','',false,80,42],['West Singhbhum','',false,130,68]];
const focusImages={
 'Ranchi':'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80',
 'East Singhbhum':'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?auto=format&fit=crop&w=900&q=80',
 'Dhanbad':'https://images.unsplash.com/photo-1473445361085-b9a07f55608b?auto=format&fit=crop&w=900&q=80',
 'Bokaro':'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=900&q=80',
 'Hazaribagh':'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=900&q=80',
 'Giridih':'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=900&q=80'};
const testimonialData=[['Aditi','Class 10, Ranchi','I feel more confident and prepared now.','assets/photos/testimonials/testimonial-1.svg'],['Pooja','Class 9, Dhanbad','Now I know my body better and I’m not afraid.','assets/photos/testimonials/testimonial-2.svg'],['Neha','Class 8, Bokaro','The session was very helpful and easy to understand.','assets/photos/testimonials/testimonial-3.svg'],['Sunita','Teacher, Hazaribagh','We can now talk about periods without shame.','assets/photos/testimonials/testimonial-4.svg'],['Rani','Class 9, Jamshedpur','This programme really cares about us.','assets/photos/testimonials/testimonial-5.svg'],['Kavya','Class 10, Giridih','I learned so much, and I’ve shared it with my friends.','assets/photos/testimonials/testimonial-6.svg']];
const galleryData=[['Community session','assets/photos/gallery/gallery-1.svg'],['Health education','assets/photos/gallery/gallery-2.svg'],['Volunteer engagement','assets/photos/gallery/gallery-3.svg'],['Periods are normal','assets/photos/gallery/gallery-4.svg'],['School outreach','assets/photos/gallery/gallery-5.svg']];
function text(id,v){const e=document.getElementById(id);if(e)e.textContent=v??'—'}
function parseCSV(csv){const rows=[];let row=[],cell='',q=false;for(let i=0;i<csv.length;i++){const c=csv[i],n=csv[i+1];if(c==='"'){if(q&&n==='"'){cell+='"';i++}else q=!q}else if(c===','&&!q){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(cell);cell='';if(row.some(v=>v!==''))rows.push(row);row=[]}else cell+=c}if(cell!==''||row.length){row.push(cell);if(row.some(v=>v!==''))rows.push(row)}if(!rows.length)return[];const headers=rows.shift().map(x=>x.trim());return rows.map(r=>Object.fromEntries(headers.map((h,i)=>[h,(r[i]??'').trim()])))}
async function fetchSheet(name){if(!ready)return[];const u=`https://docs.google.com/spreadsheets/d/${encodeURIComponent(cfg.spreadsheetId)}/gviz/tq?tqx=out:csv&sheet=${encodeURIComponent(name)}`;const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw Error('Could not read '+name);return parseCSV(await r.text())}
function applyStats(s){text('womenReached',Number(s.women_reached||0).toLocaleString('en-IN')+'+');text('sessions',Number(s.sessions||0).toLocaleString('en-IN')+'+');text('districtsReached',s.districts_reached);text('satisfaction',(s.satisfaction||0)+'%')}
function normalizeDistricts(rows){return rows.length?rows.map(r=>({name:r.name,alias:r.city_alias||'',priority:String(r.priority).toUpperCase()==='TRUE',pads:Number(r.pads_distributed||0),people:Number(r.people_helped||0),active:String(r.active).toUpperCase()!=='FALSE',description:r.description||'Community outreach, awareness and health support.'})).filter(x=>x.active):fallbackDistricts.map(x=>({name:x[0],alias:x[1],priority:x[2],pads:x[3],people:x[4],active:true,description:'Community outreach, awareness and health support.'}))}
let districts=[];
function districtLabel(d){return d.name+(d.alias?` (${d.alias})`:'')}
function focusCard(d){const bg=focusImages[d.name]||'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=900&q=80';return `<button class="focus-card" data-district="${d.name}"><div class="focus-photo" style="background-image:linear-gradient(0deg,rgba(50,13,40,.65),transparent 70%),url('${bg}')"><strong>${d.name}${d.alias?`<span>(${d.alias})</span>`:''}</strong></div><div class="focus-metrics"><div class="metric-row"><div class="metric-icon">♧</div><div><b>${d.pads.toLocaleString('en-IN')}</b><small>Pads distributed</small></div></div><div class="metric-row"><div class="metric-icon">♧</div><div><b>${d.people.toLocaleString('en-IN')}</b><small>People helped</small></div></div></div></button>`}
function miniCard(d){return `<button class="mini-district" data-district="${d.name}"><strong>${districtLabel(d)}</strong><div class="mini-metrics"><span><b>${d.pads.toLocaleString('en-IN')}</b> pads</span><span><b>${d.people.toLocaleString('en-IN')}</b> helped</span></div></button>`}
function selectDistrict(name){const d=districts.find(x=>x.name===name)||districts[0];if(!d)return;document.querySelectorAll('[data-district]').forEach(x=>x.classList.toggle('active',x.dataset.district===d.name))}
function renderDistricts(rows){districts=normalizeDistricts(rows);const focus=districts.filter(d=>d.priority).slice(0,6);document.getElementById('priorityDistricts').innerHTML=focus.map(focusCard).join('');document.getElementById('allDistricts').innerHTML=districts.map(miniCard).join('');document.querySelectorAll('[data-district]').forEach(x=>x.addEventListener('click',()=>selectDistrict(x.dataset.district)));selectDistrict('Ranchi')}
function renderContent(){document.getElementById('testimonials').innerHTML=testimonialData.map(x=>`<article class="story"><img src="${x[3]}" alt="${x[0]}"><p>“${x[2]}”</p><div class="who">— ${x[0]} · ${x[1]}</div></article>`).join('');document.getElementById('galleryGrid').innerHTML=galleryData.map(x=>`<figure><img src="${x[1]}" alt="${x[0]}"><figcaption>${x[0]}</figcaption></figure>`).join('')}
document.getElementById('showAllBtn').addEventListener('click',()=>{document.getElementById('allWrap').classList.remove('hidden');document.getElementById('showAllBtn').classList.add('hidden');document.getElementById('allWrap').scrollIntoView({behavior:'smooth',block:'start'})});document.getElementById('hideAllBtn').addEventListener('click',()=>{document.getElementById('allWrap').classList.add('hidden');document.getElementById('showAllBtn').classList.remove('hidden');document.getElementById('reach').scrollIntoView({behavior:'smooth',block:'start'})});
async function load(){renderContent();applyStats(fallbackStats);renderDistricts([]);if(!ready)return;try{const [s,d]=await Promise.all([fetchSheet('Dashboard'),fetchSheet('Districts')]);if(s[0])applyStats(s[0]);if(d.length)renderDistricts(d)}catch(e){console.warn('Google Sheets unavailable; showing starter data.',e)}}load();
